<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
<?php foreach ($flashMessenger->getMessages() as $msg): ?>
    <?php echo $msg ?>
<?php endforeach; ?>
<p>
  <a href="<?= $this->baseUrl() ?>/usuario/cadastrar/"><button type="button" class="btn btn-primary btn-lg"><i class="icon-user"> Cadastrar usuário</i></button></a>
</p>
<div class="widget wgreen">

    <div class="widget-head">
        <div class="pull-left">LISTAGEM DE USUÁRIOS</div>
        <div class="widget-icons pull-right">
            <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
            <a href="#" class="wclose"><i class="icon-remove"></i></a>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="widget-content">

        <div class="table-responsive">
            <table class="table table-hover table-bordered table-striped" id='list-usuarios'>
                <colgroup>
                    <col class="col-lg-1">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                </colgroup>
                <thead>
                    <tr class="warning">
                        <th>#</th>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Telefone</th>
                        <th>Permissão</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>

                    <? foreach ($this->paginator as $usuario): ?>
                        
                        <tr link="<?= $this->baseUrl() ?>/usuario/editar/id/<?= $usuario->cli_codigo ?>" class="td-list">
                            <td><?= $usuario->cli_codigo ?></td>
                            <td><?= $usuario->cli_nome ?></td>
                            <td><?= $usuario->cli_email ?></td>
                            <td><?= $usuario->cli_telefone ?></td>
                            <td><?= $usuario->cli_permissao ?></td>
                            <td sytle="text-align:center">
                                <div class="btn-group">
                                    <a href="<?= $this->baseUrl() ?>/usuario/perfil/id/<?= $usuario->cli_codigo ?>"><button class="btn btn-sm btn-info"><i class="icon-user"></i></button></a>

                                    <a href="<?= $this->baseUrl() ?>/usuario/editar/id/<?= $usuario->cli_codigo ?>"><button class="btn btn-sm btn-success"><i class="icon-pencil"></i></button></a>
                                    <a href="<?= $this->baseUrl() ?>/usuario/visualizar/id/<?= $usuario->cli_codigo ?>"><button class="btn btn-sm btn-primary"><i class="icon-zoom-in"></i></button></a>
                                    <a href="<?= $this->baseUrl() ?>/usuario/excluir/id/<?= $usuario->cli_codigo ?>"><button class="btn btn-sm btn-danger"><i class="icon-remove"></i></button></a>
                                </div>

                            </td>
                        </tr>
                        
                    <? endforeach; ?>  
                </tbody>
            </table>
        </div>

        <div class="widget-foot">

            <?php echo $this->paginator; ?>

            <div class="clearfix"></div> 

        </div>
    </div>
<script>
    $(function(){
        $('#list-usuarios').dataTable({
            "oLanguage": {
                "sUrl": "<?= $this->baseUrl() ?>/js/datatable/dataTables.pt-br.txt"},
            "iDisplayLength": 50,
            // "sDom": 'T<"clear">lfrtip',
            // "oTableTools": {
            //   "sSwfPath": "../media/swf/copy_csv_xls_pdf.swf"
            // },
            "aoColumnDefs": [
              { 'bSortable': false, 'aTargets': [ 0 ] }
            ],
            "aaSorting" : [[0, 'desc']],
            "bStateSave": true,    
            
            "oTableTools": {
                "aButtons": []
            }
        });
    });
</script>


