<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
<?php foreach ($flashMessenger->getMessages() as $msg): ?>
    <?php echo $msg ?>
<?php endforeach; ?>
<div class="widget wgreen">

    <div class="widget-head">
        <div class="pull-left">LISTAGEM DE USUÁRIOS | LOGS</div>
        <div class="widget-icons pull-right">
            <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
            <a href="#" class="wclose"><i class="icon-remove"></i></a>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="widget-content">

        <div class="table-responsive">
            <table class="table table-hover table-bordered table-striped">
                <colgroup>
                    <col class="col-lg-1">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                </colgroup>
                <thead>
                    <tr class="warning">
                        <th>#</th>
                        <th>Nome</th>
                        <th>Logs</th>
                    </tr>
                </thead>
                <tbody>

                    <? foreach ($this->paginator as $usuario): ?>

                        <tr link="<?= $this->baseUrl() ?>/usuario/editar/id/<?= $usuario->cli_codigo ?>" class="td-list">
                            <td><?= $usuario->cli_codigo ?></td>
                            <td><?= $usuario->cli_nome ?></td>
                            <td sytle="text-align:center">
                                <div class="btn-group">
                                    <span class="label label-primary"><a href="#">DIÁRIO</a></span>
                                    <span class="label label-success"><a href="#">SEMANAL</a></span>
                                    <span class="label label-info"><a href="#">MESAL</a></span>
                                </div>

                            </td>
                        </tr>

                    <? endforeach; ?>  
                </tbody>
            </table>
        </div>

        <div class="widget-foot">

            <?php echo $this->paginator; ?>

            <div class="clearfix"></div> 

        </div>
    </div>



