<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
<?php foreach ($flashMessenger->getMessages() as $msg): ?>
    <?php echo $msg ?>
<?php endforeach; ?>
<div class="row">

    <div class="col-md-12">

      <div class="widget wred">
        <div class="widget-head">
          <div class="pull-left">Perfil</div>
          <div class="widget-icons pull-right">
            <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
            <a href="#" class="wclose"><i class="icon-remove"></i></a>
          </div>
          <div class="clearfix"></div>
        </div>

        <div class="widget-content">
          <div class="padd">
            

            <!-- Profile form -->

            <div class="form profile">
              <div class='perfil-box-image' >
               <?=  $this->upload ?>
               <? 
                if($this->image_perfil) 
                  $image = $this->image_perfil;
                else{
                  $image = "not_found.png";
                }
               ?>
               <img src="<?= $this->baseUrl(); ?>/upload/users/<?= $image ?>" class='perfil-img'>
              </div>
              <!-- Edit profile form (not working)-->
              <?= $this->form ?> 
            </div>

          </div>
        </div>
      </div>  
      
    </div>
</div>
