<?php $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger'); ?>
<?php foreach ($flashMessenger->getMessages() as $msg): ?>
    <?php echo $msg ?>
<?php endforeach; ?>

<div class="btn-group">
    <a href="javascript:void(0);"><button class="btn btn-sm btn-info" id="addRow"><i class="icon-plus"></i></button></a>
</div>
<div class="widget wviolet">

    <div class="widget-head">
        <div class="pull-left">FREQUÊNCIA</div>
        <div class="widget-icons pull-right">
            <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
            <a href="#" class="wclose"><i class="icon-remove"></i></a>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="widget-content">

        <div class="table-responsive">
            <table class="table table-hover table-bordered table-striped" id='lista-frequencia'>
                <colgroup>
                    <col class="col-lg-1">
                    <col class="col-lg-1">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                    <col class="col-lg-2">
                </colgroup>
                <thead>
                    <tr class="warning">
                        <th>Data Agendada</th>
                        <th>Hora Agendada</th>
                        <th>Status</th>
                        <th>Observação</th>
                        <th>Ação</th>
                    </tr>
                </thead>
                <tbody>
                    <? foreach ($this->frequencia as $frequencia): ?>
                    
                        <tr>
                            <form id="form-<?php echo $frequencia->fre_id ?>" action="<?= $this->baseUrl() ?>/frequencia/cadastrar/" class="form-table" method="post">
                            <td>
                                <input type="text"  name="fre_data"   value="<?php echo ($frequencia->fre_data != "") ? $this->dateFormate($frequencia->fre_data) : ""; ?>" class="form-control data">
                                <input type="hidden"  name="fre_id"   value="<?php echo $frequencia->fre_id ?>" class="form-control data">
                                <input type="hidden"  name="tra_id_fk"   value="<?php echo $frequencia->tra_id_fk ?>" class="form-control data">
                            </td>
                            <td><input type="text" name="fre_hora"  value="<?php echo $frequencia->fre_hora ?>" class="form-control hora"></td>
                            <td>
                              <select name="fre_status">
                                <option value="">Selecione</option>
                                <option value="Presente" <?php echo ($frequencia->fre_status == "Presente") ? "selected" : ""; ?>>Presente</option>
                                <option value="Faltou" <?php echo ($frequencia->fre_status == "Faltou") ? "selected" : ""; ?>>Faltou</option>
                                <option value="Remarcou"<?php echo ($frequencia->fre_status == "Remarcou") ? "selected" : ""; ?>>Remarcado</option>
                              <select>  
                            </td>
                            <td><input type="text" name="fre_observacao" value="<?php echo $frequencia->fre_observacao ?>" class="form-control"></td>
                            <td sytle="text-align:center">
                                <button type="submit" id="<?php echo $frequencia->fre_id ?>" class="btn btn-primary button-frequencia">Enviar Dados</button>
                            </td>
                            </form>   
                        </tr>
                    <? endforeach; ?>  
                </tbody>
            </table>
        </div>

        <div class="widget-foot">

            <div class="clearfix"></div> 

        </div>
    </div>