 <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title" style="color:#1171a3">Filtrar solicitações</h3>
        </div>
        <div class="panel-body">

         <form class="form-inline" role="form" action="<?= $this->baseUrl() ?>/social/resultado/" method="post">
              
            <div class="form-group">
              <label class="sr-only" for="data_inicio">Data Inicio</label>
              <input type="text" style="max-width: 94px;" class="form-control" value="<?= $this->data_inicio ?>" id="data_inicio" name="data_inicio" placeholder="Data Início">
            </div>  
            &nbsp;
            &nbsp;

            <div class="form-group">
              <label class="sr-only" for="data_fim">Data Fim</label>
              <input type="text" style="max-width: 94px;" class="form-control" value="<?= $this->data_fim ?>"  id="data_fim" name="data_fim" placeholder="Data Fim">
            </div>  
            &nbsp;
            &nbsp;
            
            <div class="form-group">
                <select id="status" class="form-control" style="max-width: 410px;" name="status">
                    <option  value='' <?= $this->status == '' ? 'selected="selected"' : '' ?>>Status</option>
                        <option value="0" <?= $this->status == '0' ? 'selected="selected"' : '' ?>>Não Atendidas </option>
                        <option value="1" <?= $this->status == '1' ? 'selected="selected"' : '' ?>>Atendidas</option>
                </select>
            </div>
            
            &nbsp;
            &nbsp;
            <?php if (!($identity->cli_permissao == "social" || $identity->cli_tipo == 2)): ?>
            <div class="form-group">
                <select class="form-control" style="max-width: 410px;" name="operador">
                    <option value=''>Usuário</option>
                    <?php foreach ($this->opers as $operador): 
                        if($this->oper == $operador->cli_codigo) 
                            $selected = "selected='selected'";
                        else
                            $selected = '';
                    ?>
                        <option value="<?= $operador->cli_codigo ?>" <?= $selected ?>  ><?= $operador->cli_nome ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            &nbsp;
            &nbsp;
            <?php endif; ?>

            <div class="form-group">
                <select class="form-control" style="max-width: 410px;" name="cliente">
                    <option value=''>Cliente</option>
                    <?php foreach ($this->clis as $cliente): 
                        if($this->clidados == $cliente->cli_codigo) 
                            $selected = "selected='selected'";
                        else
                            $selected = '';
                    ?>
                        <option value="<?= $cliente->cli_codigo ?>" <?= $selected ?> ><?= $cliente->cli_nome ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <button type="submit"  id="submit-filtro-social" class="btn btn-danger">Filtrar</button>
        </form>

        </div>
      </div>