<!DOCTYPE html>
<html lang="pt_br" id="ng-app" ng-app="app">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta charset="utf-8"/>
  <!-- Title and other stuffs -->
  <title>Dermobook 1.0.0</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="description" content=""/>
  <meta name="keywords" content="Gerenciador promoções dermocare"/>
  <meta name="author" content="DermoCare"/>

  <!-- Stylesheets -->
  <link href="<?= $this->baseUrl() ?>/bootstrap_promocoes/css/bootstrap.min.css" rel="stylesheet"/>
  <link rel="stylesheet" href="<?= $this->baseUrl() ?>/bootstrapvalidator/dist/css/bootstrapValidator.min.css"/>
  
</head>

<body>

<div class="bs-example">
    <div class="well" style="max-width: 400px; margin: 0 auto 10px;">
      <img src="<?=$this->baseUrl()?>/img/logo_promocoes.gif"/>
      <br/>
      <br/>
      <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#myModal">
          Cadastrar participante
      </button>
      </br>
      <a href="<?= $this->baseUrl() ?>/promocoes/listar"> 
        <button type="button" class="btn btn-info btn-lg btn-block" >
          Listar participantes
        </button>
      </a>
      </br>
      <button type="button" class="btn btn-success btn-lg btn-block" id="sortear" >
        Sortear ganhador
      </button>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Cadastrar Perticipante</h4>
      </div>
      <div class="modal-body">
         <form role="form" id="registrationForm" data-bv-onsuccess="onFormSuccess">
          <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="nome" name ="nome" placeholder="Digite o nome">
          </div>

          <div class="form-group">
            <label for="email">Email</label>
            <input type="text"  name ="email"class="form-control" id="email" style="text-transform: lowercase" placeholder="Digite o Email">
          </div>

          <div class="form-group">
            <label for="telefone">Telefone</label>
            <input type="text" class="form-control" id="telefone" name="telefone" placeholder="Digite o telefone"
                data-bv-phone="true"
                data-bv-phone-country="BR"
                data-bv-phone-message="Digite o DDD mais telefone" >
          </div>
          
          <div class="form-group">
          <label for="sexo">Sexo</label>  
          <div class="radio">
            <label>
              <input type="radio" name="sexo" id="feminino" value="feminino">
              Feminino
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="sexo" id="feminino" value="masculino">
              Masculino
            </label>
          </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button type="Submit" class="btn btn-primary">Salvar</button>
      </div>
      </form>
    </div>
  </div>
</div>



<script src="<?=$this->baseUrl()?>/bootstrap_promocoes/js/jquery.js"></script>
<script src="<?=$this->baseUrl()?>/bootstrap_promocoes/js/bootstrap.min.js"></script>
<script src="<?=$this->baseUrl()?>/bootstrap_promocoes/js/jquery.maskedinput.js"></script>

<script type="text/javascript" src="<?=$this->baseUrl()?>/bootstrapvalidator/dist/js/bootstrapValidator.min.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl()?>/bootstrapvalidator/src/js/language/pt_BR.js"></script>
<script src="<?=$this->baseUrl()?>/bootstrap_promocoes/js/system.js"></script>


</body>

</html>