<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <!-- Title and other stuffs -->
        <title>DermoBook</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="">

        <!-- Stylesheets -->
        <link href="<?= $this->baseUrl() ?>/style/bootstrap.css" rel="stylesheet">
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/style/font-awesome.css">
        <link href="<?= $this->baseUrl() ?>/style/style.css" rel="stylesheet">


        <!-- HTML5 Support for IE -->
        <!--[if lt IE 9]>
        <script src="js/html5shim.js"></script>
        <![endif]-->

        <!-- Favicon -->
        <link rel="shortcut icon" href="<?= $this->baseUrl() ?>/img/favicon/favicon.png">
    </head>

    <body>

        <!-- Form area -->
        <div class="admin-form">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <!-- Widget starts -->
                        <div class="widget worange">
                            <!-- Widget head -->
                            <div class="widget-head">
                                <i class="icon-lock"></i> Login 
                            </div>

                            <?php $authNamespace = new Zend_Session_Namespace('Zend_Auth');?>
                            <div class="widget-content">
                                <div id="mensagem">Usuario ou senhas errados</div>
                                <div class="padd">
                                    <!-- Login form -->
                                    <form class="form-horizontal" action="<?=$this->baseUrl()?>/login/" name="basic_validate" id="basic_validate" novalidate="novalidate">
                                        <!-- Email -->
                                        <div class="form-group">
                                            <label class="control-label col-lg-3" for="login">Email</label>
                                            <div class="col-lg-9">
                                                <span class="add-on"></span><input type="text" class="form-control" id="login" name="login" placeholder="Email" 
                                                value="<?= $authNamespace->user ?>">
                                            </div>
                                        </div>
                                        <!-- Password -->
                                        <div class="form-group">
                                            <label class="control-label col-lg-3" for="senha">Senha</label>
                                            <div class="col-lg-9">
                                                <input type="password" class="form-control" id="senha" name="senha" placeholder="Senha" 
                                                value="<?php echo $authNamespace->password ?>">
                                            </div>
                                        </div>
                                        <!-- Remember me checkbox and sign in button -->
                                        <div class="form-group">
                                                            <div class="col-lg-9 col-lg-offset-3">
                                                              <div class="checkbox">
                                                                <label>
                                                                  <input type="checkbox" name="lembrar" id="lembrar" value="1"  <?php if($authNamespace->lembrar){echo"checked";}?> >Lembrar-me
                                                                </label>
                                                                </div>
                                                            </div>
                                        </div>
                                        <div class="col-lg-9 col-lg-offset-3">
                                            <button type="submit" class="btn btn-danger" id="btn-login"data-loading-text="Verificando acesso..."data-complete-text="Logar">Logar</button>
                                            <button type="reset" class="btn btn-default">Limpar</button>
                                        </div>
                                        <br />
                                    </form>

                                </div>
                            </div>

                            <div class="widget-foot">
                                <div id="direitos">&reg;Tokem Web Technology</div>
                            </div>
                        </div>  
                    </div>
                </div>
            </div> 
        </div>



        <!-- JS -->
       <script src="<?=$this->baseUrl()?>/js/validate/jquery.min.js"></script>
         <script src="<?=$this->baseUrl()?>/js/validate/jquery.ui.custom.js"></script>
         <script src="<?=$this->baseUrl()?>/js/validate/bootstrap.min.js"></script>
         <script src="<?=$this->baseUrl()?>/js/validate/jquery.uniform.js"></script>
         <script src="<?=$this->baseUrl()?>/js/validate/jquery.chosen.js"></script>
         <script src="<?=$this->baseUrl()?>/js/validate/jquery.validate.js"></script>
         <script src="<?=$this->baseUrl()?>/js/validate/unicorn.js"></script>
         <script src="<?=$this->baseUrl()?>/js/validate/unicorn.form_validation.js"></script>
         <script src="<?=$this->baseUrl()?>/js/jquery-login.js"></script>
    </body>
</html>