 <div class="row">
            <div class="col-md-12"> 
              
              <ul class="stat-boxes" id="charts-box" style="display:block">
              <li>
                <a href="javascript:void(0)" id="chart-afazer">
                <div class="left peity_bar_good"><span>2,4,9,7,12,10,12</span></div>
                <div class="right">
                  <strong id="graf01"></strong>
                  Pacientes
                </div>
              </a>
              </li>
              <li>
                <a href="javascript:void(0)" id="chart-andamento">
                <div class="left peity_bar_neutral"><span>2,4,9,7,12,10,12</span></div>
                <div class="right">
                  <strong id="graf02"></strong>
                  Usuários
                </div>
              </a>
              </li>
              <li>
                <a href="javascript:void(0)" id="chart-atrasados">
                <div class="left peity_bar_bad"><span>2,4,9,7,12,10,12</span></div>
                <div class="right">
                  <strong id="graf03"></strong>
                  Mailer
                </div>
              </a>
              </li>
              <!-- <li>
                <a href="javascript:void(0)" id="chart-concluidos">
                <div class="left peity_bar_good_conc"><span>2,4,9,7,12,10,12</span></div>
                <div class="right">
                  <strong id="graf04"><?php echo $this->countConcluidas; ?></strong>
                </div>
              </a>
              </li> -->

             <!--  <li>
                <a href="javascript:void(0)" id="chart-finalizados">
                <div class="left peity_bar_good_end"><span>2,4,9,7,12,10,12</span></div>
                <div class="right">
                  <strong id="graf05"><?php echo $this->countFinalizadas; ?></strong>
                </div>
              </a>
              </li> -->
            </ul>

            </div>
          </div>
<hr/>





