<?php 
    $auth = Zend_Auth::getInstance();
    $identity = $auth->getIdentity();
    
    $request = Zend_Controller_Front::getInstance()->getRequest();
    $controller = $request->getControllerName();
?>

<ul class="navi">

    <!-- Use the class nred, ngreen, nblue, nlightblue, nviolet or norange to add background color. You need to use this in <li> tag. -->
    
    <li class="has_submenu nred <?=$controller == "tratamento" ? "current\" " : "";?>">
        

        <a href="#">
            <i class="icon-desktop"></i>Tratamentos
            <!-- Icon for dropdown -->
            <span class="pull-right"><i class="icon-angle-right"></i></span>    
        </a>
        <ul>
            <li><a href="<?=$this->baseurl()?>/tratamento/nome">Cadastrar</a></li>
            <li><a href="<?=$this->baseurl()?>/tratamento/">Listar</a></li>
        </ul>
    </li>

    
    <!-- Menu with sub menu -->
    <li class="has_submenu ngreen <?=$controller == "usuario" ? "current\" " : "";?>">
        <a href="#">
            <!-- Menu name with icon -->
            <i class="icon-user"></i>Usuários 
            <!-- Icon for dropdown -->
            <span class="pull-right"><i class="icon-angle-right"></i></span>
        </a>

        <ul>
            <li><a href="<?=$this->baseurl()?>/usuario/cadastrar">Cadastrar</a></li>
            <li><a href="<?=$this->baseurl()?>/usuario/">Listar</a></li>
<!--            <li><a href="/usuario/logs">Logs</a></li>-->
        </ul>
    </li>
        
    <li class="has_submenu nviolet <?=$controller == "cliente" ? "current\" " : "";?>">
        <a href="#">
            <!-- Menu name with icon -->
            <i class="icon-list"></i>Clientes 
            <!-- Icon for dropdown -->
            <span class="pull-right"><i class="icon-angle-right"></i></span>
        </a>

        <ul>
            <li><a href="<?=$this->baseurl()?>/cliente/cadastrar">Cadastrar</a></li>
            <li><a href="<?=$this->baseurl()?>/cliente/">Listar</a></li>
        </ul>
    </li>

    <li class="has_submenu nblue <?=$controller == "financeiro" ? "current\" " : "";?>">
        <a href="#">
            <!-- Menu name with icon -->
            <i class="icon-book"></i>Financeiro 
            <!-- Icon for dropdown -->
            <span class="pull-right"><i class="icon-angle-right"></i></span>
        </a>

        <ul>
            <li><a href="<?=$this->baseurl()?>/financeiro/">Listar</a></li>
        </ul>
    </li>

    <li class="has_submenu norange <?=$controller == "suporte" ? "current\" " : "";?>">
        <a href="#">
            <!-- Menu name with icon -->
            <i class="icon-wrench"></i>Suporte 
            <!-- Icon for dropdown -->
            <span class="pull-right"><i class="icon-angle-right"></i></span>
        </a>

        <ul>
            <li><a href="<?=$this->baseurl()?>/suporte/problemas">Problemas</a></li>
            <li><a href="<?=$this->baseurl()?>/suporte/melhorias">Melhorias</a></li>
        </ul>
    </li>
</ul>