<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <!-- Title and other stuffs -->
  <title>Erro - DUCAJOBS</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="author" content="">

  <!-- Stylesheets -->
  <link href="<?php echo $this->baseUrl()?>/style/bootstrap.css" rel="stylesheet">
  <!-- Font awesome icon -->
  <link rel="stylesheet" href="<?php echo $this->baseUrl()?>/style/font-awesome.css">
  <!-- Main style sheet -->
  <link href="<?php echo $this->baseUrl()?>/style/style.css" rel="stylesheet">
  <!-- Responsive Bootstrap -->
  
  
  <!-- HTML5 Support for IE -->
  <!--[if lt IE 9]>
  <script src="js/html5shim.js"></script>
  <![endif]-->

  <!-- Favicon -->
  <link rel="shortcut icon" href="img/favicon/favicon.png">
</head>

<body>

<!-- Form area -->
<div class="error-page">
  <div class="container-fluid">

    <div class="row-fluid">
      <div class="span12">
        <!-- Widget starts -->
            <div class="widget wblue">
              <!-- Widget head -->
              <div class="widget-head">
                <i class="icon-question-sign"></i> Erro 
              </div>

              <div class="widget-content">
                <div class="padd error">
                  
                  <h1>Erro 404 Recurso não encontrado!!</h1>
                  <p>Por favor verifique a URL digitada e tente novamente, se estiver certo que esta tudo correto pode ser que o recurso não faça mais parte do sistema</p>
                  <br />
                                 
                 <br />
                 <div class="horizontal-links">
                  <a href="<?php echo $this->baseUrl()?>/tarefa/">Visão geral</a> | <a href="<?php echo $this->baseUrl()?>/suporte/problemas">Suporte</a>
                 </div>

                </div>
              </div>
                <div class="widget-foot">
                  <!-- Footer goes here -->
                </div>
            </div>  
      </div>
    </div>
  </div> 
</div>
	
		

<!-- JS -->
<script src="js/jquery.js"></script>
<script src="js/bootstrap.js"></script>
</body>
</html>